### ISSUE TITLE
Android App? 

### ISSUE THREAD

**Issue by LunarGem** [DraqueT/PolyGlot#497] opened 2017-09-18 15:44 UTC
Not sure if I should have just emailed you about this, but did you ever think about an Android version? I'm learning Android development and I'd totally do the UI/UX if you were willing to put the functionality in it. Android is in Java too so it shouldn't be too difficult, and I just thought a mobile version would be so useful to the conlang community (being that this is the best lexicon app I've found and so much of our time is mobile nowadays). What do you think?

**Comment by DraqueT** [comment] 2017-09-18 15:58
That would be fantastic! Honestly, I don't know anything about android dev, but if you wanted to take a crack at this, I will provide any support that you need in terms of understanding the programming interfaces that I've provided in the code.

I think the best approach might be first identifying what functionality is going to be pulled across. We'll want to do so in a way that ensures that you've got objects which just sit on top of existing ones. We shouldn't start with the goal of reproducing the entirety of PolyGlot, as that would be pretty overwhelming as an initial push.

Let me know if you are up for chatting on the subject or something. I have telegram and a handful of other clients that I use. :3

**Comment by LunarGem** [comment] 2017-09-18 16:02
Probably the first thing I would do would make it so you could view an already created lexicon from a .pgd file, just the words/definitions/conjugations but that will at least let you learn your language on the go and show it to people. Then I would do editing and adding words, and maybe after that add some of the other cool things PolyGlot does.

**Comment by DraqueT** [comment] 2017-09-18 16:18
I absolutely agree there. That should actually be pretty easy to do. Once you load up a dictionary core and have it open a file, the lexicon is something that you can very easily pull. You won't even really need to worry about how it works behind the scenes.

**Comment by LunarGem** [comment] 2017-09-18 16:28
Work on this would be really slow, but I'm oddly excited so we'll see how soon I get a releasable product. 😀 I'll ask if I have questions!

**Comment by DraqueT** [comment] 2017-09-18 17:38
Sounds good! Be sure to do a pull on your fork from mine before you start work (although the interfaces you'll be accessing should be very stable at this point). If you could create a folder labeled Clients in the root level of the project and a subfolder Android in there, that would be a good place to drop this element of the project. ^^

**Comment by DraqueT** [comment] 2018-01-10 16:20
Closing this particular ticket since a fork exists. 

Be sure to pull the latest changes before putting more work in, some stuff has changed!

**Comment by Huy-Ngo** [comment] 2020-02-21 12:28
Hi, I've come here with the same issue in mind. I've just looked at @LunarGem's fork and it seems it is abandoned (there were only two commits from 2 years ago). I'm not sure if I could handle this, but I'm interested in continuing this. Do you have a developer's doc available or do you have any instruction on where to start on your project?

**Comment by DraqueT** [comment] 2020-02-21 20:55
Hey there, thanks for the interest! There are a few things to keep in mind.

First, the place to start is definitely here: https://github.com/DraqueT/PolyGlotPDF

PolyGlotPDF is a repo that is still in Java 8 (I upgraded to Java 12 not long ago so that I could distribute runnable images). This is going to be much easier to work with than the main repo. Although the code is not maintained to the same level as the main repo, this is what is used to generate PDF files (as the PDF library I use is not Jaa9+ compatible), so if any kind of breaking change is introduced, PolyGlotPDF will have code pushed which will address this.

As for the code itsellf: 
DictCore is going to be what you care about the most. This is what you will use to load and save language files. You can read with the readFile() method, and I will have to add the write file code back in (since it's not used with the PDF reading, typically).

Once you've loaded a file, the collections and managers within the DictCore will contain all of the language data that you'll need. I think the first point of attack should be consuming the wordCollection object. This contains ConWord nodes, each of which represents a word of a constructed language. You can pull the font that the language uses from the propertiesManager object. I don't know whether Android Java uses fonts of the same type, so you might have to do some work there, but at their outset, fonts are loaded as byte arrays, so you can just strip out my font handling past that point and use whatever is native in an Android environment.

My email is draquemail@gmail.com, so please send any other questions you might have there! I'll be very happy to help in any way that I'm able, and I know that there are a lot of users that would be incredibly happy to have a mobile client for PolyGlot! : )

**Comment by LunarGem** [comment] 2020-02-23 16:54
Yeah, I realized my skill level was not quite up to the challenge and while trying to get better moved to college to study software engineering instead of web and mobile so it's safe to say I probably won't be working on this for a while. Hopefully you can get it working!

**Comment by DraqueT** [comment] 2020-04-10 03:52
Closing this issue, as it now has its own repo and project.

**Closed by DraqueT** 2020-04-10 03:52 UTC

**Comment by pe1uca** [comment] 2021-04-24 20:27
@DraqueT which is the repo and project for the android app?  
I was thinking on giving it a try myself, but would like to know what already has been done to not make double efforts.

**Comment by DraqueT** [comment] 2021-04-24 20:42
@pe1uca 
Here's the repo where it was begin: https://github.com/Huy-Ngo/PolyGlotAndroid

I would recommend against using this repo, though. The easiest path forward would be to use the code from PolyGlot 2.5 as a base. This was the last version that was compiled on Java 8 (higher versions are not compatible with Android). Additionally, I think it would be best to cut out most of the more advanced features, at least initially. I can help with re-implementing those. All of the basic functionality has been in place since 2.5 and has remained unchanged in terms of how it saves. 

If you move forward with this, I can provide assistance regarding overall functionality and how various features work. ^^

**Comment by pe1uca** [comment] 2021-04-24 21:41
Got it, I'll keep checking only the original repo.  

What I was thinking to do first is try to decouple the UI from the core functionality, that way it'll be easier to port and upgrade the android version.

Will check the differences between current version and 2.5 to see what is the best approach.  
As you mentioned in the changelog of 3.0 the main reason to upgrade was to allow easier multi-platform deploy, maybe the core can remain Java 8 compatible and just the UI functionality attached to a greater version.  

Quickly I could only find two issues with this approach:

- This switch statement https://github.com/DraqueT/PolyGlot/blob/master/src/main/java/org/darisadesigns/polyglotlina/Nodes/LexiconProblemNode.java#L37-L42
- Using String.isBlank()

Do you have any other higher java version specific feature in the core? Not about handling UI or OS specific functionality like IO.

**Comment by DraqueT** [comment] 2021-04-24 21:53
Hrm, that's not a bad point. Most of the newest core code can be converted back to Java8 with pretty minimal effort, honestly. There are a few places in the core that will have to be changed (it keeps track of the top level window, and a handful of other things), but the underlying structures should be pretty clean.

The biggest gotchas I see you running into is that I have a custom encoding method for pictures that are embedded in textboxes (you can copy/paste an image into the definition box if you want to see that in action).

**Comment by pe1uca** [comment] 2021-04-24 22:17
Yes, the track of the main window is one of the things I'm checking to extract from the core and handle it in a different way.  
Also the use of any `java.awt` and `javax` (so far those are the ones that I saw caused issues).  

I'll check that encoding part to see what needs to be done, as mentioned `java.awt.image.BufferedImage` will need to be changed.
