### ISSUE TITLE
Unable to check for update 

### ISSUE THREAD

**Issue by LeGrandCthulhu** [DraqueT/PolyGlot#1227] opened 2022-12-21 16:51 UTC
When trying to check for update, Polyglot tell me `The element type "hr" must be terminated by the matching end-tag "</hr>".` It seems to be an html problem but I dunno what to do.

**Comment by DraqueT** [comment] 2023-01-26 01:06
Thank you for reporting this! I'm currently trying to reproduce this, but not able to reproduce it. Could you please send me the Polyglot_error.log file from your <USER>/Polyglot directory? That will help me track down the issue you're seeing there.

**Comment by DraqueT** [comment] 2023-03-19 01:42
Unable to reproduce and no other reports of this. Closing for now.

**Closed by DraqueT** 2023-03-19 01:42 UTC
