### ISSUE TITLE
Autoconjugation Rules are not applied to different classes, only work with one

### ISSUE THREAD

**Issue by mcholiday** [DraqueT/PolyGlot#693] opened 2019-04-16 22:47 UTC
I apologize in advance for my stupidity and poor English!
I have a language that has genderspecific adjectives. For example some adjectives only apply to gender dominant, some to objective and some only to submissive. I use the newest version of polyglot.
I created the classes all, dominant, dominant/objective, dominant/submissive, and submissive. I assigned every adjective a class.
This happens: I have the form Singular Dominant. I have one rule and I copied ot 4 times. One applies to all (not capital All, but my created class), one to dominant, one to dominant/objective, and one to dominant/submissive. It is the exact same rule copied. It looks exactly the same. Adjectives with all are working perfectly, they are displaying all possible forms. But words with dominant class who should display all dominant forms show nothing. The same applies to my other genders. The only one working is all. But the rules are identical! I tried changing the order of the rules, deleting all but all and copying all again then changing the class those new copies apply to. Do you have any ideas what I did wrong! I am most thankful for your kindness and patience!

**Comment by DraqueT** [comment] 2019-04-18 00:18
Thank you for taking the time to write this up! I will definitely check this out and get you a beta once it's corrected. ^^

**Comment by DraqueT** [comment] 2019-04-18 00:27
Could you please send me your language file? I am not able to reproduce this, and would like to take a look. My email is draquemail@gmail.com. I'll help get this corrected for you. :)

**Comment by mcholiday** [comment] 2019-04-19 12:11
Thank you, I sent it to you, but my email often is in Spam; so if it is gone, I will send it again with a different email. And thank you! I wish you a good Easter holiday!

**Comment by DraqueT** [comment] 2019-06-10 22:35
Hello! I am sorry to have taken so long to get back to you, but I hope I can still help. Could you send the language file a second time please? I am having trouble finding it (if it was in Spam, it has since been wiped).

I hope that PolyGlot has continued to be a useful tool to you! :)

**Comment by DraqueT** [comment] 2019-06-26 23:32
Hello! I found your file and think that I figured out the issue you've been having! Try this out:

1) go to the POS window in your language
2) select Adjective
3) click Conjugation/Declension autogeneration
4) find the forms that you wish to apply to other class values of adjective
5) in these, make sure that you select the class they should apply to in the "Match by Class Value" option checkboxes. 

I am closing this ticket now, but if this does not address your problem, please reply to reopen it!

**Closed by DraqueT** 2019-06-26 23:32 UTC
Labels: bug
