### ISSUE TITLE
Null Pointer Exception on Linux with Multicore

### ISSUE THREAD

**Issue by zauberparacelsus** [DraqueT/PolyGlot#143] opened 2015-03-19 21:29 UTC
I am finding that most of the time, PolyGlot will crash with a Null Pointer Exception on startup under Linux.  Given that my computer is a quad-core and the crash is threading related, that may be a factor.

Further, the crash ceases to happen at all if I force it to run on a specific core with the taskset command.

```
# force command to only run on core0
taskset -c 0 java -jar PolyGlot.jar
```

When the crash occurs, the command line error output I get is:

```
Exception in thread "main" java.lang.NullPointerException
	at javax.swing.plaf.nimbus.NimbusStyle.validate(NimbusStyle.java:298)
	at javax.swing.plaf.nimbus.NimbusStyle.getValues(NimbusStyle.java:806)
	at javax.swing.plaf.nimbus.NimbusStyle.getInsets(NimbusStyle.java:485)
	at javax.swing.plaf.synth.SynthStyle.installDefaults(SynthStyle.java:913)
	at javax.swing.plaf.synth.SynthLookAndFeel.updateStyle(SynthLookAndFeel.java:264)
	at javax.swing.plaf.synth.SynthLabelUI.updateStyle(SynthLabelUI.java:69)
	at javax.swing.plaf.synth.SynthLabelUI.propertyChange(SynthLabelUI.java:299)
	at java.beans.PropertyChangeSupport.fire(PropertyChangeSupport.java:335)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:327)
	at java.beans.PropertyChangeSupport.firePropertyChange(PropertyChangeSupport.java:263)
	at java.awt.Component.firePropertyChange(Component.java:8393)
	at javax.swing.JComponent.addNotify(JComponent.java:4734)
	at java.awt.Container.addImpl(Container.java:1114)
	at javax.swing.CellRendererPane.addImpl(CellRendererPane.java:106)
	at java.awt.Container.add(Container.java:410)
	at javax.swing.plaf.basic.BasicComboBoxUI.getSizeForComponent(BasicComboBoxUI.java:1408)
	at javax.swing.plaf.basic.BasicComboBoxUI.getDisplaySize(BasicComboBoxUI.java:1352)
	at javax.swing.plaf.basic.BasicComboBoxUI.getMinimumSize(BasicComboBoxUI.java:920)
	at javax.swing.plaf.basic.BasicComboBoxUI.getPreferredSize(BasicComboBoxUI.java:909)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1652)
	at javax.swing.GroupLayout$ComponentSpring.calculateNonlinkedPreferredSize(GroupLayout.java:3019)
	at javax.swing.GroupLayout$ComponentSpring.calculateNonlinkedMinimumSize(GroupLayout.java:3005)
	at javax.swing.GroupLayout$ComponentSpring.calculateMinimumSize(GroupLayout.java:2972)
	at javax.swing.GroupLayout$Spring.getMinimumSize(GroupLayout.java:1336)
	at javax.swing.GroupLayout$ComponentSpring.calculatePreferredSize(GroupLayout.java:2979)
	at javax.swing.GroupLayout$Spring.getPreferredSize(GroupLayout.java:1346)
	at javax.swing.GroupLayout$ComponentSpring.getBaseline(GroupLayout.java:3073)
	at javax.swing.GroupLayout$BaselineGroup.calculateBaselineAndResizeBehavior(GroupLayout.java:2732)
	at javax.swing.GroupLayout$BaselineGroup.calculateSize(GroupLayout.java:2708)
	at javax.swing.GroupLayout$Group.calculatePreferredSize(GroupLayout.java:1602)
	at javax.swing.GroupLayout$Spring.getPreferredSize(GroupLayout.java:1346)
	at javax.swing.GroupLayout$Group.getSpringSize(GroupLayout.java:1638)
	at javax.swing.GroupLayout$Group.calculateSize(GroupLayout.java:1627)
	at javax.swing.GroupLayout$Group.calculatePreferredSize(GroupLayout.java:1602)
	at javax.swing.GroupLayout$Spring.getPreferredSize(GroupLayout.java:1346)
	at javax.swing.GroupLayout$Group.getSpringSize(GroupLayout.java:1638)
	at javax.swing.GroupLayout$Group.calculateSize(GroupLayout.java:1622)
	at javax.swing.GroupLayout$Group.calculatePreferredSize(GroupLayout.java:1602)
	at javax.swing.GroupLayout$Spring.getPreferredSize(GroupLayout.java:1346)
	at javax.swing.GroupLayout$Group.getSpringSize(GroupLayout.java:1638)
	at javax.swing.GroupLayout$Group.calculateSize(GroupLayout.java:1622)
	at javax.swing.GroupLayout$Group.calculatePreferredSize(GroupLayout.java:1602)
	at javax.swing.GroupLayout$Spring.getPreferredSize(GroupLayout.java:1346)
	at javax.swing.GroupLayout.calculateAutopadding(GroupLayout.java:1071)
	at javax.swing.GroupLayout.prepare(GroupLayout.java:1059)
	at javax.swing.GroupLayout.preferredLayoutSize(GroupLayout.java:878)
	at java.awt.Container.preferredSize(Container.java:1788)
	at java.awt.Container.getPreferredSize(Container.java:1773)
	at javax.swing.JComponent.getPreferredSize(JComponent.java:1654)
	at javax.swing.GroupLayout$ComponentSpring.calculateNonlinkedPreferredSize(GroupLayout.java:3019)
	at javax.swing.GroupLayout$ComponentSpring.calculateNonlinkedMinimumSize(GroupLayout.java:3005)
	at javax.swing.GroupLayout$ComponentSpring.calculateMinimumSize(GroupLayout.java:2972)
	at javax.swing.GroupLayout$Spring.getMinimumSize(GroupLayout.java:1336)
	at javax.swing.GroupLayout$Group.getSpringSize(GroupLayout.java:1636)
	at javax.swing.GroupLayout$Group.calculateSize(GroupLayout.java:1624)
	at javax.swing.GroupLayout$Group.calculateMinimumSize(GroupLayout.java:1598)
	at javax.swing.GroupLayout$Spring.getMinimumSize(GroupLayout.java:1336)
	at javax.swing.GroupLayout$Group.getSpringSize(GroupLayout.java:1636)
	at javax.swing.GroupLayout$Group.calculateSize(GroupLayout.java:1624)
	at javax.swing.GroupLayout$Group.calculateMinimumSize(GroupLayout.java:1598)
	at javax.swing.GroupLayout$ParallelGroup.calculateMinimumSize(GroupLayout.java:2569)
	at javax.swing.GroupLayout$Spring.getMinimumSize(GroupLayout.java:1336)
	at javax.swing.GroupLayout$Group.getSpringSize(GroupLayout.java:1636)
	at javax.swing.GroupLayout$Group.calculateSize(GroupLayout.java:1622)
	at javax.swing.GroupLayout$Group.calculateMinimumSize(GroupLayout.java:1598)
	at javax.swing.GroupLayout$Spring.getMinimumSize(GroupLayout.java:1336)
	at javax.swing.GroupLayout.calculateAutopadding(GroupLayout.java:1068)
	at javax.swing.GroupLayout.prepare(GroupLayout.java:1058)
	at javax.swing.GroupLayout.minimumLayoutSize(GroupLayout.java:896)
	at java.awt.Container.minimumSize(Container.java:1840)
	at java.awt.Container.getMinimumSize(Container.java:1825)
	at javax.swing.JComponent.getMinimumSize(JComponent.java:1736)
	at javax.swing.GroupLayout$ComponentSpring.calculateNonlinkedMinimumSize(GroupLayout.java:3008)
	at javax.swing.GroupLayout$ComponentSpring.calculateMinimumSize(GroupLayout.java:2972)
	at javax.swing.GroupLayout$Spring.getMinimumSize(GroupLayout.java:1336)
	at javax.swing.GroupLayout$Group.getSpringSize(GroupLayout.java:1636)
	at javax.swing.GroupLayout$Group.calculateSize(GroupLayout.java:1624)
	at javax.swing.GroupLayout$Group.calculateMinimumSize(GroupLayout.java:1598)
	at javax.swing.GroupLayout$ParallelGroup.calculateMinimumSize(GroupLayout.java:2569)
	at javax.swing.GroupLayout$Spring.getMinimumSize(GroupLayout.java:1336)
	at javax.swing.GroupLayout$Group.getSpringSize(GroupLayout.java:1636)
	at javax.swing.GroupLayout$Group.calculateSize(GroupLayout.java:1624)
	at javax.swing.GroupLayout$Group.calculateMinimumSize(GroupLayout.java:1598)
	at javax.swing.GroupLayout$Spring.getMinimumSize(GroupLayout.java:1336)
	at javax.swing.GroupLayout$Group.getSpringSize(GroupLayout.java:1636)
	at javax.swing.GroupLayout$Group.calculateSize(GroupLayout.java:1622)
	at javax.swing.GroupLayout$Group.calculateMinimumSize(GroupLayout.java:1598)
	at javax.swing.GroupLayout$ParallelGroup.calculateMinimumSize(GroupLayout.java:2569)
	at javax.swing.GroupLayout$Spring.getMinimumSize(GroupLayout.java:1336)
	at javax.swing.GroupLayout$Group.getSpringSize(GroupLayout.java:1636)
	at javax.swing.GroupLayout$Group.calculateSize(GroupLayout.java:1622)
	at javax.swing.GroupLayout$Group.calculateMinimumSize(GroupLayout.java:1598)
	at javax.swing.GroupLayout$Spring.getMinimumSize(GroupLayout.java:1336)
	at javax.swing.GroupLayout.calculateAutopadding(GroupLayout.java:1068)
	at javax.swing.GroupLayout.prepare(GroupLayout.java:1058)
	at javax.swing.GroupLayout.minimumLayoutSize(GroupLayout.java:896)
	at java.awt.Container.minimumSize(Container.java:1840)
	at java.awt.Container.getMinimumSize(Container.java:1825)
	at javax.swing.JComponent.getMinimumSize(JComponent.java:1736)
	at javax.swing.plaf.basic.BasicTabbedPaneUI$TabbedPaneLayout.calculateSize(BasicTabbedPaneUI.java:2303)
	at javax.swing.plaf.basic.BasicTabbedPaneUI$TabbedPaneLayout.minimumLayoutSize(BasicTabbedPaneUI.java:2282)
	at java.awt.Container.minimumSize(Container.java:1840)
	at java.awt.Container.getMinimumSize(Container.java:1825)
	at javax.swing.JComponent.getMinimumSize(JComponent.java:1736)
	at javax.swing.GroupLayout$ComponentSpring.calculateNonlinkedMinimumSize(GroupLayout.java:3008)
	at javax.swing.GroupLayout$ComponentSpring.calculateMinimumSize(GroupLayout.java:2972)
	at javax.swing.GroupLayout$Spring.getMinimumSize(GroupLayout.java:1336)
	at javax.swing.GroupLayout$ComponentSpring.calculatePreferredSize(GroupLayout.java:2979)
	at javax.swing.GroupLayout$Spring.getPreferredSize(GroupLayout.java:1346)
	at javax.swing.GroupLayout$Group.getSpringSize(GroupLayout.java:1638)
	at javax.swing.GroupLayout$Group.calculateSize(GroupLayout.java:1622)
	at javax.swing.GroupLayout$Group.calculatePreferredSize(GroupLayout.java:1602)
	at javax.swing.GroupLayout$Spring.getPreferredSize(GroupLayout.java:1346)
	at javax.swing.GroupLayout$Group.getSpringSize(GroupLayout.java:1638)
	at javax.swing.GroupLayout$Group.calculateSize(GroupLayout.java:1622)
	at javax.swing.GroupLayout$Group.calculatePreferredSize(GroupLayout.java:1602)
	at javax.swing.GroupLayout$Spring.getPreferredSize(GroupLayout.java:1346)
	at javax.swing.GroupLayout$SequentialGroup.setValidSize(GroupLayout.java:2017)
	at javax.swing.GroupLayout$Group.setSize(GroupLayout.java:1587)
	at javax.swing.GroupLayout.calculateAutopadding(GroupLayout.java:1079)
	at javax.swing.GroupLayout.layoutContainer(GroupLayout.java:918)
	at java.awt.Container.layout(Container.java:1503)
	at java.awt.Container.doLayout(Container.java:1492)
	at java.awt.Container.validateTree(Container.java:1688)
	at java.awt.Container.validateTree(Container.java:1697)
	at java.awt.Container.validateTree(Container.java:1697)
	at java.awt.Container.validateTree(Container.java:1697)
	at java.awt.Container.validate(Container.java:1623)
	at java.awt.Container.validateUnconditionally(Container.java:1660)
	at java.awt.Window.show(Window.java:1033)
	at java.awt.Component.show(Component.java:1655)
	at java.awt.Component.setVisible(Component.java:1607)
	at java.awt.Window.setVisible(Window.java:1014)
	at PolyGlot.PFrame.setVisible(PFrame.java:109)
	at PolyGlot.ScrDictInterface.main(ScrDictInterface.java:268)
```

**Comment by DraqueT** [comment] 2015-03-20 13:58
Thank you for the heads up! I will spin up a Linux virtual later today to investigate this issue. I really appreciate the full stack trace that you included as well, that already shows me exactly where the error is taking place!

**Comment by DraqueT** [comment] 2015-03-25 03:08
I just tried this in a multicore environment with Ubuntu and haven't been able to reproduce... what flavor and build of Linux are you using? That might help me track down where this is going wonky.

**Comment by DraqueT** [comment] 2016-07-19 14:04
I have not been able to repeat this, and the form in question (scrDictInterface) has since been scrapped/replaced, so I am closing  the ticket. 

NOTE: The problem seemed to take place in PFrame.setVisible() on the line where super is being called... no idea how "super" can be null while "this" is instantiated properly.

**Closed by DraqueT** 2016-07-19 14:04 UTC
Labels: bug
