### ISSUE TITLE
Custom Font Ligatures

### ISSUE THREAD

**Issue by hokumi** [DraqueT/PolyGlot#565] opened 2018-05-23 05:03 UTC
Hey, I just finished creating a font for my conlang after soooo much effort and time spent on FontForge and it isn't working properly on PolyGlot. 
The only way I could see for making what I wanted to happen happening was by using ligatures on my fontype. So my aa, th, ee... would be a single character and not two. So apparently ligatures don't display on PolyGlot and this is really sad haha. So if you could make this happen I'd be very glad (: Thank you.

**Comment by DraqueT** [comment] 2018-05-23 13:32
Heyo! Thanks for creating a ticket about this. This is definitely a bug, as ligatures _should_ be working everywhere in PolyGlot (except print to PDF).

Could you let me check out the font you created and give me a sequence of keystrokes that reproduces the issue? That will definitely help me track it down.

**Comment by hokumi** [comment] 2018-05-23 15:37
Here it is: https://ufile.io/08kbv
None of the keystrokes are working. Ligatures should happen when I press aa, ee, ii, oo, th, sh, kk, pp, tt, mn and ff. All of them upper and lower cases.

**Comment by scottgit** [comment] 2018-05-23 18:53
I've noticed this issue also

**Comment by DraqueT** [comment] 2018-05-25 15:13
Seems like this is tied to an update in recent versions of Java, which is why it's showing up now. I need to figure out how to turn the feature for respecting font ligatures back on.

**Comment by DraqueT** [comment] 2018-06-04 19:08
As a heads up, I'm closing this ticket, as it's a duplicate of #540 .

**Closed by DraqueT** 2018-06-04 19:08 UTC
Labels: bug, duplicate
