### ISSUE TITLE
Feature Request: Android Port

### ISSUE THREAD

**Issue by ceafin** [DraqueT/PolyGlot#659] opened 2019-01-28 03:01 UTC
Since it's Java and all, I thought maybe an Android release as a feature request wouldn't be /too/ outlandish?

**Comment by DraqueT** [comment] 2019-02-13 20:13
Heyo! Thank you for the comment! Porting to Android is something that I'm open to, but I would definitely need help with something like that. If anyone is looking to fork the project or you know folks that are good with Android dev, I would be very happy to work with them/explain the architecture of PolyGlot. : )

**Comment by utkucandogan** [comment] 2019-11-18 21:23
I can try to port it even though I am not very experienced in android. However, I am eager to become experienced in order to make this porting happen :)

**Comment by DraqueT** [comment] 2019-11-18 21:33
Hey, thank you for the interest! And I'm here to answer questions/help with the port generally.

The first thing that I think would really need to be done is identifying which features would come over. The big reason for this is that PolyGlot is currently on Java 12, and identifying which elements need to be scaled back to J8 compatibility will be important.

Take a bit to check out some of the code and let me know what you think generally/whether you have any questions.

**Comment by utkucandogan** [comment] 2019-11-19 16:25
Well I started to look into it and I must say this port will not be easy :sweat_smile:. The main reason is that gui and io system must be rewritten entirely. Gui part is, I think, easier. However io system is going to be hard due to the difference in file permissions.

For now, I will try to obtain a base by chopping off some dependencies. Can you tell me which files and functions are required for a working lexicon implementation. For that, I exclude the conjugations, etymology and logographs feature.

**Comment by DraqueT** [comment] 2019-11-19 20:34
Wall of text for you here, but I'm trying to address a lot. Let me know if you want to move communication to email or even have a phone discussion or something. For the moment, I'm pretty free to work on PolyGlot as a larger project generally. Also, def want to give you as much support here as I can! Jump to the bottom of this for a conclusion summary if you would like to read that before going through the lengthy explanation of some of the basics.

So I just realized something that I should have thought of a lot earlier. Outside the UI, there is ALREADY a J8 version of Polyglot which has all core components. Check out this project: https://github.com/DraqueT/PolyGlotPDF . I maintain this base due to the library I use for PDF generation being fundamentally incompatible with modules. I apologize for some of the bad style choices that still exist in this code, but most of the architectural cleanup I did came with the upgrade to J12. Whether you choose to use this older code or want to base it off the newer code is up to you. The older code is all J8, but it's also architecturally messier. I'm doing some minor cleanup of the old code today in just as a heads up.

Anyhow, to answer your other questions:

DictCore is what ties everything together, and should be the primary focus as you pull things over. You won't need all of what's in it to implement the Lexicon, but I think you should leave the general structure in case you decide to implement more later. It contains instances of all of the custom managers/collections, which organize all the sets of data that make up a language. The PolyGlot class itself is used mostly for startup and is tied very closely to the desktop experience. I don't ultimately think there is anything you'll require in it.

Within the managers and collections, nodes are what hold individual chunks of data. Those objects will be what you are reading from primarily. You will find a lot of interdependence between the various nodes and managers. This is largely due to the fact that in spoken language, *everything potentially touches everything*, and I didn't want to preclude weird linguistic choices from people who were looking to build something novel.

For the lexicon, you will primarily leverage the ConWordCollection object, though I would recommend importing the majority of the classes in Managers and Nodes. Most of the swing imports remaining have to do with fonts, and I presume there are direct corollaries for Android projects. Below are the ones you can easily exclude:

MANAGERS/COLLECTIONS:
OptionsManager - options for the UI of PolyGlot (though does contain reversion count, which you can either do away with or let users set in a different way)
VisualStyleManager - More UI stuff
ImageCollection - as with ImageNode, you might or might not want to keep this. You can just kill it for now and pull later if you want to deal exclusively with text for early iterations.

NODES:
ImageNode - You might or might not want to re-implement this. Notes fields within word objects can contain references to images. For initial implementation maybe just ignore that, and it can be handled at a later time.
LogoNode - Also contains images. This is the node for logographic characters. If you kill this, you can kill the LogoCollection as well. As a heads up, not many people use this feature.
NOTE: IOHandler awt dependencies

Now we get into how things are populated from an archived PolyGlot language. For this, the main classes used are CustHandler, CustHandlerFactory, and IOHandler. The IOHandler class is where I've tried to isolate most of the system IO stuff for PolyGlot. This might contain some of the biggest challenges for porting over, but I also think that most of the logic can remain the same. With luck, you'll only have to swap out how you're getting streams, and maybe wrap it in something that collects the correct permissions. The CustHandler stuff deals with reading the custom XML format that all of PolyGlot's text saves use.

If you want to inspect a PolyGlot language file itself to really get a sense for what the program is dealing with at the most basic level, they are just zip archives. Maybe try making a file that leverages a bit of everything, saving, then taking a look inside (remember that you can do things like pasting images into larger text boxes such as the definition field).

PGTUtil contains tons and tons of constants. Some of these are static values which are generated at load time and which you will probably be able to strip out.

CONCLUSION:

If you're looking to just get a stripped down lexicon you need to be able to 
1) Read polyglot files (CustHandler objects should need minimal work, IOHandler will require more)
2) Instantiate a DoctCore which contains a ConWordCollection
3) Populate ConWord objects to the ConWordCollection (more advanced features can be commented out, all you will really need initially is the plain text values)
4) Read from the ConWordCollection to populate a new UI

The fourth will probably be the most work, as the UI that exists for PolyGlot is Swing.

**Comment by utkucandogan** [comment] 2019-11-22 19:54
After I tried a lot of things, I am sorry to say that but I couldn't handle porting. What I can do is however is completely rewriting an app that can import pgd files. But that makes it a completely new project and I am actually not sure if I can handle it. Sorry for raising false hope.

**Comment by DraqueT** [comment] 2019-11-22 23:55
Hrm. Could you handle just writing the interface and the file IO stuff? Honestly, I would not have much trouble creating a J8 based system that could read and provide you with all the information you need. The android UI and file operations are what I am ultimately unfamiliar with.

**Comment by DraqueT** [comment] 2020-03-02 04:04
Duplicate of #497 closing.

**Closed by DraqueT** 2020-03-02 04:04 UTC
Labels: Request, enhancement, help wanted
