### ISSUE TITLE
Line breaks being edited out of definition.

### ISSUE THREAD

**Issue by electric-snake** [DraqueT/PolyGlot#403] opened 2017-03-13 04:21 UTC
Useful for words with multiple definitions

**Comment by DraqueT** [comment] 2017-03-13 12:46
On deselecting and reselecting a definition, line breaks are edited out. This is due to definitions now being saved in HTML. On both the front and backend, have '\n' -> "<br>" and vice versa.

**Comment by lucymhdavies** [comment] 2017-03-13 13:38
If it's saving in HTML format, I suppose it could be updated to '\n' -> "<br>" and vice versa?

**Comment by DraqueT** [comment] 2017-03-16 13:12
Now inserting line breaks where they don't belong... reopening.

**Comment by DraqueT** [comment] 2017-03-27 14:22
After clean/rebuild, unable to reproduce error... might have been files failing to build correctly after I modified them. Closing.

**Closed by DraqueT** 2017-03-27 14:22 UTC
Labels: bug
