### ISSUE TITLE
Config Load Failure

### ISSUE THREAD

**Issue by bcburin** [DraqueT/PolyGlot#1269] opened 2023-04-06 15:57 UTC
Whenever I try to open PolyGlot, I get a "Config Load Failure" window with the message "Unable to load options file or file corrupted: For input string: '1.0' ".

I had the beta version installed and tried to downgrade to the stable version, because I was unable to save my progress in it. However, after removing the package with apt and re-installing the stable one, I started to get the error described before whenever I tried to open the application.

This is the error log [PolyGlot_error.log](https://github.com/DraqueT/PolyGlot/files/11172343/PolyGlot_error.log)

My OS is Ubuntu 22.04.

**Comment by TrapinchO** [comment] 2023-04-06 18:17
look for "polyglot.ini" file (or something similar since it is on linux) and delete it

the issue is most likely that the newer config file has fields that are not in the older version

**Comment by DraqueT** [comment] 2023-04-06 21:19
Yup, deleting the ini should do it! The issue is that the newer version supports decimal values there but the old version did not. Closing the ticket since this is the solution, but please feel free to reopen if you continue to have trouble.

**Closed by DraqueT** 2023-04-06 21:19 UTC
