### ISSUE TITLE
Open Recent not working with folders with non-ASCII characters

### ISSUE THREAD

**Issue by SergioMejia2** [DraqueT/PolyGlot#699] opened 2019-05-18 01:23 UTC
Hi, every time I use the Recent option to open my recent files, I get an error because the program cannot find the file. This is because the folder where the file is has an "é" in its name, which the program doesn't get so it cannot find the file.
But, for example, the Save option saves the file right (reading the "é" just fine).

Hope you can fix this :D

**Comment by DraqueT** [comment] 2019-05-18 04:01
Thanks for the write up and for how specific you are with the failing scenario! As one follow up question, are you using a PC, a Mac, or Linux?

**Comment by SergioMejia2** [comment] 2019-05-18 11:19
Windows 10 exactly

**Comment by DraqueT** [comment] 2019-06-04 20:17
Heyo! Just wanted to give you an update here before closing this issue. I have tested this pretty extensively across a few systems and have been unable to reproduce this error. I think there are two possibilities. 

1) The version of Java you are using should be updated. If that's the case, you can update it by going to Control Pannel->Programs->Java->Update(tab)->Update Now(button

2) There's an edge case that I have not accounted for. If updating does not fix this problem, please reply here to re-open the ticket and we will proceed from there. I'll need to take a look at your PolyGlot.cfg file if that is the case, and hopefully that will be able to give some clues.

**Closed by DraqueT** 2019-06-04 20:17 UTC
Labels: bug
