### ISSUE TITLE
File Read Error

### ISSUE THREAD

**Issue by zohar-github** [DraqueT/PolyGlot#1179] opened 2022-05-20 20:40 UTC
![image](https://user-images.githubusercontent.com/100376945/169606782-ff06772a-9a08-4f54-a8bb-2c5842e5f150.png)
This issue started this morning when I went to go open the file and this popped up, and I have not been able to open my saved file since. 

Copy and pasted error in case the image does not load: File Read Error: The element type "dictionary" must be terminated by the matching  end-tag "</dictionary>"

Any help is appreciated.

**Comment by ItzShiney** [comment] 2022-05-21 04:04
Open the language file as a zip archive and send us the `PGDictionary.xml` file from there

**Comment by zohar-github** [comment] 2022-05-21 17:45
Thank you so much!

**Comment by ItzShiney** [comment] 2022-05-21 18:26
Am I blind or is there nothing attached

**Comment by zohar-github** [comment] 2022-05-21 18:35
Ah I think the attachment didn't show up at first because I initially replied and attached it from email. Doing it from the thread now! Thank you for the patience, I'm new to this, but its appreciated.

[1653078608_xxTEMPPGTFILExx1653027374 (extract.me).zip](https://github.com/DraqueT/PolyGlot/files/8748150/1653078608_xxTEMPPGTFILExx1653027374.extract.me.zip)

**Comment by ItzShiney** [comment] 2022-05-21 19:50
[Zapara.zip](https://github.com/DraqueT/PolyGlot/files/8748268/Zapara.zip)

I just added these lacking tags at the end of the file: `</decGenRule></declensionCollection></dictionary>`

**Comment by DraqueT** [comment] 2022-05-22 04:23
Heyo, thank you @zohar-github for reporting and thank you @ItzShiney  for the assist! I also believe I have found the root cause of this... I am traveling, but this is a big enough bug that I might try to release an update to fix it. 

Please let me know if it causes you any more trouble!

**Comment by DraqueT** [comment] 2022-05-24 19:05
Closing this for now, but wanted to give a few notes, @zohar-github .

1) If you have more troubles with this, please feel free to re-open this issue here.
2) I believe that this hole has actually been plugged by a rework of the saving logic that has been done since the last major release. Try downloading the latest beta build here: https://draquet.github.io/PolyGlot/

**Closed by DraqueT** 2022-05-24 19:05 UTC
