### ISSUE TITLE
Intermittent graphical bug on mouseover

### ISSUE THREAD

**Issue by Kandosii** [DraqueT/PolyGlot#912] opened 2020-06-10 16:07 UTC
I've been enjoying using PolyGlot (on Win10), but I'm getting an occasional graphics bug on mouseover (see attached image). It may potentially have something to do with tooltips: it can occur without keystroke input, simply by moving the mouse somewhere. Everything still functions, and navigating to a new tab fixes the view, but as soon as a tooltip pops up, it breaks again. This happens in all popup menus, including the save menu. Haven't been able to find a way to stop it apart from exiting the program. The only alteration I've made to settings is to up font size to 13.5.
![Bug example](https://user-images.githubusercontent.com/11417077/84290573-d7b55380-ab11-11ea-8dcb-aa2c1146b062.png)

**Comment by DraqueT** [comment] 2020-06-13 19:33
Heyo, thank you for reporting this! 

I am having some trouble reproducing this, is there anything that you do which makes the graphical bug activate? Once it activates, is there anything you have found which makes it correct itself? Once I'm able to reproduce the error I'll be able to start tracking it down to quash it.

**Comment by Exocamp** [comment] 2020-09-12 18:48
Hello there.

I've been having this issue too, also on Windows 10. From what I can tell, there is no definite trigger to the bug - it is almost entirely at random. Situations where I've had it commonly before include adding entries such as part of speech and conjugation, mousing over tabs, and when a new window opens - however, this is not always the case. The issue is fixed when I maximize the window, and is fine when I de-maximize it.

Hope this helps.

**Comment by Exocamp** [comment] 2020-09-12 21:01
Quick update: it seems maximizing the window only fixes it once. After that, the problem persists.

**Comment by DraqueT** [comment] 2021-12-17 00:47
This bug SHOULD be fixed now. Leaving open for a few weeks to see if it reemerges, but will close shortly after if not.

**Closed** 2021-12-17 00:56 UTC
Labels: bug
