### ISSUE TITLE
cursor in definition section of lexicon displaying in wrong place, becoming more skewed to the right the more characters are added

### ISSUE THREAD

**Issue by bayden-woodland** [DraqueT/PolyGlot#695] opened 2019-04-17 17:04 UTC
UPDATE x2:

Requested language file from user (difficulty reproducing problems).

UPDATE:

I am using Mac OSMojave v10.14.3
The behaviour seems to be in the "definition" section of the lexicon-- the box where I would write the definitions of my words.
Here is my font information:
ConLang Font: (custom), plain, size 16
Local Font: Charis SIL, plain, size 12

Perhaps the cursor is adjusting to the width of my ConLang font, even though the definition is written in the local font? That's the most natural idea that occurs to me. My conlang font is hard to read when too small, so I upped the size, but I love to make efficient use of screen real estate so I kept my local font small.

ORIGINAL TEXT:

In all three of the following photos, the writing cursor is actually adjacent to the last letter. There are no spaces or tabs in this text box.

<img width="644" alt="Screen Shot 2019-04-17 at 10 02 22 AM" src="https://user-images.githubusercontent.com/12058957/56306744-18753080-60f8-11e9-9ac8-394ead3aa5e7.png">

<img width="646" alt="Screen Shot 2019-04-17 at 10 02 42 AM" src="https://user-images.githubusercontent.com/12058957/56306746-1a3ef400-60f8-11e9-8ad2-ab0fd139e043.png">

<img width="643" alt="Screen Shot 2019-04-17 at 10 03 07 AM" src="https://user-images.githubusercontent.com/12058957/56306750-1c08b780-60f8-11e9-8bda-0380a446da53.png">

**Comment by DraqueT** [comment] 2019-04-18 19:25
Thanks for taking the time to write this up and report the bug! I do have a couple of questions, since I'm having trouble reproducing it.

1) What OS are you using?
2) Where exactly in PolyGlot are you seeing this behavior? That is to say, which screen and which text area?
3) Are there any special options that you have checked for your language, and is that a custom font version?

I'll definitely look into this and try to get it corrected for you! ^^

**Comment by DraqueT** [comment] 2019-06-04 20:45
Having difficulty reproducing bug. Tried on mac OS 10.14.3, 10.13.6, and on Win 10. Used provided user file in all cases. This bug seems to be dependent on system state/some edge case not yet considered in PolyGlot yet.

Suggested user try updating Java to latest version and seeing if that cleared up the issue.

**Comment by DraqueT** [comment] 2019-10-31 20:14
The font rendering system in Java has been mostly reworked since Java 8 and I have been unable to reproduce this after extensive testing. I am cautiously closing this bug to be reopened if users experience the error after 3.0 release...

**Closed by DraqueT** 2019-10-31 20:14 UTC
Labels: !Reproduce, bug, help wanted
