### ISSUE TITLE
Word generator uses only conlang font (bug)

### ISSUE THREAD

**Issue by wanderwitch** [DraqueT/PolyGlot#1157] opened 2022-03-13 02:37 UTC
DEVELOPER TEXT
In the word generator, the Categories text box and Syllable Types text box should use local lang fonts rather than conlang fonts.

ORIGINAL TEXT
Word generator uses only the conlang where it should use the local lang
![image](https://user-images.githubusercontent.com/40308373/158042486-b8797d7e-1042-49bf-971e-7257f83fc1e2.png)

**Comment by DraqueT** [comment] 2023-07-18 01:00
After thinking about this hard, I realized this was not a bug, but a missing feature. Closing this, but opening the following ticket:

https://github.com/DraqueT/PolyGlot/issues/1312

**Closed by DraqueT** 2023-07-18 01:00 UTC
Labels: bug
