### ISSUE TITLE
Regex character selection in pronunciation not working properly

### ISSUE THREAD

**Issue by BovusSanctus** [DraqueT/PolyGlot#129] opened 2015-03-03 10:01 UTC
In the Character pronunciation guide, regex statements that start with ^ are ignored. When trying different options to match the correct pattern, it is not possible to distinguish between characters at the beginning of a word and those in the middle. The documentation seems to indicate otherwise. Search patterns that end in $ work fine.
I think the following bit of code in PronunciationMgr.java is the problem:

                // skip if set as starting characters, but later in word
                if (pattern.startsWith("^") && !isFirst) {
                    continue;
                }

                // make starting pattern if not already, and have it return the character group
                if (!pattern.startsWith("^")) {
                    pattern = "^(" + pattern + ").*";
                }
(lines 232 - 240)
It seems to me that this bit of code turns every pattern that doesn't start with ^ into one that does, but that doesn't seem very practical to me. I hope this helps in solving this issue!

**Comment by DraqueT** [comment] 2015-03-03 19:34
Thanks for the heads up and code review, BovusSanctus!

The code you see there is actually correct (given that I'm consuming the strings in chunks, attempting different regex patterns in order of priority). The problem is that it's missing the logic to properly handle regex patterns that begin with "^" in the case that they are checking the beginning of the word string.

Anyhow, this will be fixed in build 0.9.9 which will be out as soon as I finish documentation of new features. Thank you again for the catch!

**Comment by DraqueT** [comment] 2015-03-03 19:34
corrected

**Closed by DraqueT** 2015-03-03 19:34 UTC
Labels: bug

**Comment by BovusSanctus** [comment] 2015-05-08 09:43
Hey Draque,

Thanks for your messages. Your emails got sent to my junk folder,
so that's why I didn't reply. Sorry about that.

Great to hear that you've fixed the issue! I will try it out soon :)

**Comment by DraqueT** [comment] 2015-05-08 21:34
Glad to hear you're still using PolyGlot! I'm working to get version 1.0 out  on a reasonable schedule at this point. :3
