### ISSUE TITLE
Revamp Alphabetic order

### ISSUE THREAD

**Issue by dannYves** [DraqueT/PolyGlot#428] opened 2017-04-28 17:00 UTC
ADDITION:
Per user comments below, change how alphabetic order is handled. Make the UI more helpful/intuitive.

Additionally, the comma delimited alpha ordering does not seem to be working properly.

ORIGINAL MESSAGE:
Proper description of 'alphabetical order' is a bit vague.. I had to redo the alphabetic order many times because of this. For example, I have several letters that reuse letters:
Ⲓ̈Ⲉ = j , Ⲓ̈ = j , Ⲓ = i 

And it would be nice to type out the alphabet order in a more organized, aesthetically pleasing way within the app rather than grouping them all together where it can be difficult to see some of the characters next to others. For example:
All together the separate letters  Ⲓ Ⲓ́  Ⲓ̈ Ⲓ̈Ⲉ appear in the alphabetical order like:  ⲒⲒ́Ⲓ̈Ⲓ̈Ⲉ .. I not only get confused looking at that but not sure if the app will also get confused.

There should also be an option to 'ignore/include special characters', for example:
"include"  ' [apostrophes ] => 'Ⲛ  /ɛn/  
or "ignore"  - [dashes] in the alphabet) - in other words allowing us to take control of what is included in the alphabet.

And finally some terms I am unfamiliar with or they can have dubious meanings without detailed descriptions, for example:  Local Language, Local Lang Word, thus leading to improper unintentional usage of categories.

**Comment by dannYves** [comment] 2017-04-29 12:10
Here's some screen shots for you, which will also show what another user stated about the font being too small:
![alphabet order](https://cloud.githubusercontent.com/assets/28152639/25555372/37d20c80-2cb3-11e7-82a5-e8aa2f01fbfa.PNG)
![capture](https://cloud.githubusercontent.com/assets/28152639/25555373/40f728cc-2cb3-11e7-8ce4-52f3d5c3afa2.PNG)

**Comment by DraqueT** [comment] 2017-04-29 15:24
Thanks for your interest in PolyGlot! The alphabetic order menu is pretty clunky and old, and I definitely need to update it. 

It can do what you need, though! If you have special characters that combine, then PolyGlot can handle it. Put a comma between each of the characters you use, with the special characters grouped together. This will tell the program what you are trying to do, and it should respect this.

Let me know if this is helpful!

**Comment by dannYves** [comment] 2017-04-30 01:10
> Thanks for your interest in PolyGlot!

Of course!! I love your application, you did a fantastic job with it and it does just what I need it to :-) nothing out there like it :-) ... Just like any computer program it will always have bugs, need periodic updates, changes to UI, ect as technology evolves and users continue to grow.

>  It can do what you need, though! If you have special characters that combine, then PolyGlot can handle it. Put a comma between each of the characters you use, with the special characters grouped together. This will tell the program what you are trying to do, and it should respect this.
Let me know if this is helpful!

I did as you suggested:
![alphabet list small](https://cloud.githubusercontent.com/assets/28152639/25560353/7296a148-2d1f-11e7-84c4-f2f9f9601dc1.PNG)


I put <Ï,ÏⲈ> in that order
![i example](https://cloud.githubusercontent.com/assets/28152639/25560364/b6ff373c-2d1f-11e7-9624-6a3f2f5b98ac.PNG)


But <Ï> still seems to come after <ÏⲈ>
![lexicon example](https://cloud.githubusercontent.com/assets/28152639/25560361/b1b2d8e2-2d1f-11e7-9478-add6acd14eab.PNG)

It's not seemingly acknowledging the different letters despite the same letter being used. I also have a few words without auto-population in the dictionary, maybe this has something to do with it?! Not sure.

**Comment by DraqueT** [comment] 2017-05-02 14:25
Again, thanks for the detailed reports! This is definitely going to be a combination enhancement and bug correction here. PolyGlot is definitely not parsing the order you have there correctly.

The application is 100% unicode compatible, so I don't think that's the problem. The problem is probably that the alphabetization code is some of the oldest that exists, and I didn't do a great job putting it together back before I knew the project was going to get as big as it is. XD

**Comment by DraqueT** [comment] 2017-05-17 22:09
Ok... after some extensive messing with this, I have found the problem. If you make the change, then you have to swap back and forth twice from the Lexicon for it to "take." 

That is just a workaround, obviously. I'm getting to fixing the issue at the moment

**Comment by dannYves** [comment] 2017-05-30 11:46
> Ok... after some extensive messing with this, I have found the problem. If you make the change, then you have to swap back and forth twice from the Lexicon for it to "take."

That is just a workaround, obviously. I'm getting to fixing the issue at the moment


I appreciate it at the least :-)  Oh trust me, I was at for a few days trying to figure out exactly what was going on because I am very meticulous with alphabetic order in lexicons and dictionaries. I will continue to use the workaround until it is hopefully resolved in future releases :-)

**Comment by DraqueT** [comment] 2017-05-30 18:34
Closing this and opening a separate ticket for the enhancement portion.

The bug is fixed in the current build! Thanks again for helping me recognize/correct it. :3

**Closed by DraqueT** 2017-05-30 18:34 UTC
Labels: bug
