### ISSUE TITLE
Issues with the Unicode Supplemental Multilingual Plane

### ISSUE THREAD

**Issue by tanadrin** [DraqueT/PolyGlot#1158] opened 2022-03-15 18:16 UTC
When attempting to use Unicode characters from the Supplemental Multilingual Plane in the Lexicon, at least from the Gothic alphabet (𐌰𐌱𐌲𐌳 etc., codepoints U+10330–U+1034F), in the "Conlang Word" field for an entry, an error appears. For example, the input 𐌳𐌰𐌲𐍃 results in the error "Word: "𐌳𐌰𐌲𐍃" with local value: "day" cannot be rendered properly using font: Ulfilas."

This error appears regardless of the conlang font used and whether or not it supports these characters, regardless of whether or not a fallback font exists and the application displays it correctly (in all tested examples, the application displayed the characters correctly using fallback fonts or the chosen conlang font even in the error message itself), and even though no actual error in rendering seems to be occurring. Even the auto-declension feature is working normally. However, the presence of an error prevents adding additional entries to the Lexicon. 

I have reproduced this error with Old Turkic characters from the SMP, using the Segoe UI Symbol font which supports them; however, I don't have fonts that cover most of the SMP. I was unable to find any characters in the BMP that exhibited similar behavior.

Screenshot attached.

![possible-bug](https://user-images.githubusercontent.com/9657406/158442273-09d3b72d-5b57-4690-8e8b-e57cd097b578.png)

**Comment by DraqueT** [comment] 2022-03-18 18:54
Could you please send me the language file in question? I am having trouble recreating this, and I am wondering whether there's some edge case that is more complex than the string "𐌳𐌰𐌲𐍃" by itself. My email is draquemail@gmail.com and you can toss it there as an attachment.

**Comment by DraqueT** [comment] 2022-04-05 01:03
I am closing this ticket as I am not able to reproduce or get a copy of the broken language file, but if you continue to have trouble with this or can send it to me, I will reopen.

**Closed by DraqueT** 2022-04-05 01:03 UTC
Labels: bug
