### ISSUE TITLE
PoS pattern check error

### ISSUE THREAD

**Issue by OddMemories** [DraqueT/PolyGlot#939] opened 2020-10-01 22:06 UTC
DEV TEXT
1) When checking word legality, throw out malformed regex check values.
2) When doing a check language (from tools menu), check that regex values are all kosher for PoS pattern.
3) Update default text for PoS pattern so it's no longer called "type."

ORIGINAL USER TEXT
After accidentally leaving a meta character in without the dot in front of it (ie: * instead of .*), I have been stuck in an endless loop of errors and I cannot get out of it. The OK button doesn't work, and the x button just brings it back.

**Comment by DraqueT** [comment] 2020-10-01 22:35
Yikes, that is bad.

Could you tell me what screen this happens to you on and exactly how you got to it? I'll need to know how to reproduce the error on my end before I'm able to correct it.

Thanks for taking the time too write up a ticket, by the way! This is the only way that I can really know I need to correct any given bug that I don't see myself.

**Comment by OddMemories** [comment] 2020-10-02 00:50
![image](https://user-images.githubusercontent.com/72232322/94877057-54947200-040e-11eb-8d37-37077fd4c10a.png)

The general gist of what happened is that on the Parts of speech tab, I put *ur as the verb definition instead of .*ur

then when I tried to create a word... this happened

The error message also pushes itself to the front of my screen, so it's not like it will just disappear 

![image](https://user-images.githubusercontent.com/72232322/94877160-97eee080-040e-11eb-93a4-43f7e33291ed.png)

**Comment by OddMemories** [comment] 2020-10-02 00:52
Update: now it's got a copy I can drag around, but another copy appeared that is currently frozen in the middle of my screen.

**Comment by DraqueT** [comment] 2020-10-02 01:52
You might be able to hit Ctrl+S to save yuor existing work, but I'm not certain that will register with PolyGlot. If that's the case, then the work you've done since your last save might unfortunately be lost.

To close it, you can force quit via the Task Manager. I'm looking into fixes for the specific problem you've encountered to prevent it from happening agin.

**Comment by DraqueT** [comment] 2020-10-02 02:00
As a heads up, you have made me aware of an entire **class** of potential issue to check for. Sorry that you ran into this difficulty, but thank you for making me aware of it so I can fix it!

**Comment by OddMemories** [comment] 2020-10-02 04:52
It gives me a chance to fix some of the overcomplicated garbage I made before, thank god xD

Thank you though, and I'm glad I could help.

**Closed** 2020-10-05 00:36 UTC
Labels: bug
